appName: simplehelm
gitRepo:
  gitProvider: rajGit                              # <-- replace with your GitRepo integration name
  path: RjSH1/jfrog-pipelines-helm-deploy-sample      # <-- replace jfrog with your username or org name
  branch: main

appImage:
  registry: rajArt                                    # <-- replace with your Artifactory integration name
  registryUrl: "demo.jfrog-pipelines.com/cst-docker"             # <-- replace with the url to your Artifactory environment
  repoName: cst-docker

appChart:
  sourceArtifactory: rajArt                           # <-- replace with your Artifactory integration name
  repoName: cst-helm

runtime:
  k8s_integration: my_k8s                             # <-- replace with your Kubernetes integration name
  namespace: pipe-master-pool                               # <-- replace with the name of the Kubernetes namespace where the Helm chart will be deployed
  releaseName: simplehelm
